/* Generated by the Nim Compiler v2.3.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555163 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555851 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555165 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555164 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555161 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555162 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33555157 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI704643201 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI704643200 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1006633044 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI704643201 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "message", len: 0, typ: NTI33554450, name: "message", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}]};
NTI704643201.node = NNI704643201;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
var NNI33555157 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555157.node = NNI33555157;
NTI33555167.base = NTI33555157;
NTI704643201.base = NTI33555167;
NTI704643200.base = NTI704643201;
var NNI1006633044 = {kind: 1, offset: "reason0", len: 0, typ: NTI704643200, name: "reason0", sons: null};
NTI1006633044.node = NNI1006633044;
NTI1006633044.base = NTI33555157;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555162 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555162.node = NNI33555162;
NTI33555164.base = NTI33555161;
NTI33555165.base = NTI33555161;
var NNI33555161 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555164, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555165, name: "up", sons: null}]};
NTI33555161.node = NNI33555161;
NTI33555161.base = NTI33555157;
NTI33555162.base = NTI33555161;
NTI134217741.base = NTI33555162;
NTI134217743.base = NTI134217741;
var NNI33555851 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555851.node = NNI33555851;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555162;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555162;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555163 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555163.node = NNI33555163;
NTI33555163.base = NTI33555161;
NTI134217746.base = NTI33555163;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555162;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557337 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2885(ti_p2))) {
      result_33557337 = src_p1;
      }
      else {
        result_33557337 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557337 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557337 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557337 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557337 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557337, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557337 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557337 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557337 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557337[i] = nimCopy(result_33557337[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557337 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557337 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557337[i] = nimCopy(result_33557337[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557337 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557337 = src_p1;
      break;
    }

  return result_33557337;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557450 = false;

  BeforeRet: {
    var x_33557451 = obj_p0;
    if ((x_33557451 == subclass_p1)) {
    result_33557450 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557451 == subclass_p1))) break Label2;
          if ((x_33557451 == null)) {
          result_33557450 = false;
          break BeforeRet;
          }
          
          x_33557451 = x_33557451.base;
        }
    };
    result_33557450 = true;
    break BeforeRet;
  };

  return result_33557450;

}

function toJSStr(s_p0) {
  var result_33556926 = null;

    var res_33556980 = newSeq__system_u2523((s_p0).length);
    var i_33556981 = 0;
    var j_33556982 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556981 < (s_p0).length)) break Label2;
          var c_33556983 = s_p0[i_33556981];
          if ((c_33556983 < 128)) {
          res_33556980[j_33556982] = String.fromCharCode(c_33556983);
          i_33556981 += 1;
          }
          else {
            var helper_33557009 = newSeq__system_u2523(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557010 = c_33556983.toString(16);
                  if ((((code_33557010) == null ? 0 : (code_33557010).length) == 1)) {
                  helper_33557009.push("%0");;
                  }
                  else {
                  helper_33557009.push("%");;
                  }
                  
                  helper_33557009.push(code_33557010);;
                  i_33556981 += 1;
                  if ((((s_p0).length <= i_33556981) || (s_p0[i_33556981] < 128))) {
                  break Label3;
                  }
                  
                  c_33556983 = s_p0[i_33556981];
                }
            };
++excHandler;
            try {
            res_33556980[j_33556982] = decodeURIComponent(helper_33557009.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556980[j_33556982] = helper_33557009.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556982 += 1;
        }
    };
    if (res_33556980.length < j_33556982) { for (var i = res_33556980.length ; i < j_33556982 ; ++i) res_33556980.push(null); }
               else { res_33556980.length = j_33556982; };
    result_33556926 = res_33556980.join("");

  return result_33556926;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2187(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557377 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557377 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557377;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557372 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557372 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557372;

}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 219;
F.filename = "hashes.nim";
var objectID_771752114 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function catch__asyncjs95examples952_u55(future_p0, onReject_p1) {
  var result_1006633019 = null;

  var F = {procname: "catch.catch", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
    F.line = 269;
    F.filename = "asyncjs.nim";
    result_1006633019 = future_p0.catch(onReject_p1);
  framePtr = F.prev;

  return result_1006633019;

}

function isFatPointer__system_u2885(ti_p0) {
  var result_33557319 = false;

  BeforeRet: {
    result_33557319 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557319;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function add__system_u1950(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace__system_u2094(f_p0) {
  var result_33556528 = [[]];

    var it_33556533 = f_p0;
    var i_33556534 = 0;
    var total_33556535 = 0;
    var tempFrames_33556536 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555851);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556533 == null)) && (i_33556534 <= 63))) break Label2;
          tempFrames_33556536[i_33556534].Field0 = it_33556533.procname;
          tempFrames_33556536[i_33556534].Field1 = it_33556533.line;
          tempFrames_33556536[i_33556534].Field2 = it_33556533.filename;
          i_33556534 += 1;
          total_33556535 += 1;
          it_33556533 = it_33556533.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556533 == null))) break Label4;
          total_33556535 += 1;
          it_33556533 = it_33556533.prev;
        }
    };
    result_33556528[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556535 == i_33556534))) {
    nimAddStrStr(result_33556528[0], [40]);;
    nimAddStrStr(result_33556528[0], HEX24__systemZdollars_u14((total_33556535 - i_33556534)));;
    nimAddStrStr(result_33556528[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556569 = 0;
      var colontmp__1006633120 = 0;
      colontmp__1006633120 = (i_33556534 - 1);
      var res_1006633122 = colontmp__1006633120;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_1006633122)) break Label7;
            j_33556569 = res_1006633122;
            nimAddStrStr(result_33556528[0], cstrToNimstr(tempFrames_33556536[j_33556569].Field2));;
            if ((0 < tempFrames_33556536[j_33556569].Field1)) {
            nimAddStrStr(result_33556528[0], [40]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556528, 0, tempFrames_33556536[j_33556569].Field1);
            if (false) {
            nimAddStrStr(result_33556528[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u241(result_33556528, 0, 0);
            }
            
            nimAddStrStr(result_33556528[0], [41]);;
            }
            
            nimAddStrStr(result_33556528[0], [32,97,116,32]);;
            add__system_u1950(result_33556528, 0, tempFrames_33556536[j_33556569].Field0);
            nimAddStrStr(result_33556528[0], [10]);;
            res_1006633122 -= 1;
          }
      };
    };

  return result_33556528[0];

}

function rawWriteStackTrace__system_u2187() {
  var result_33556620 = [];

    if (!((framePtr == null))) {
    result_33556620 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace__system_u2094(framePtr)), NTI33554449);
    }
    else {
      result_33556620 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556620;

}

function newSeq__system_u2523(len_p0) {
  var result_33556959 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 651;
    F.filename = "system.nim";
    result_33556959 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556959[i] = null; }  framePtr = F.prev;

  return result_33556959;

}

function isNimException__system_u2025() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556460 = null;

    if (isNimException__system_u2025()) {
    result_33556460 = lastJSError;
    }
    

  return result_33556460;

}

function raiseDefect() {
    if (isNimException__system_u2025()) {
    var e_33556671 = getCurrentException();
    if (isObj(e_33556671.m_type, NTI33555162)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556671);
    }
    
    e_33556671.trace = nimCopy(null, rawWriteStackTrace__system_u2187(), NTI33554449);
    throw e_33556671;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556665 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556665[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556665[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556665[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556665[0], [32,91]);;
    add__system_u1950(buf_33556665, 0, e_p0.name);
    nimAddStrStr(buf_33556665[0], [93,10]);;
    nimAddStrStr(buf_33556665[0], rawWriteStackTrace__system_u2187());;
    var cbuf_33556666 = toJSStr(buf_33556665[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556666);
  }
  else {
    throw cbuf_33556666;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_318767312 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_318767312, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_318767326 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_1006633115 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_1006633115 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_318767326 = i_1006633115;
            F.line = 47;
            result_p0[result_p0_Idx][chckIndx(addInt(old_318767312, iHEX60gensym4_318767326), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_318767326), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_1006633115 = addInt(i_1006633115, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}
async function fn__asyncjs95examples952_u8(n_p0) {
  var result_1006632971 = null;

  var F = {procname: "asyncjs_examples_2.fn", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
    if ((7 <= n_p0)) {
    F.line = 251;
    F.filename = "asyncjs.nim";
    raiseException({message: ([102,111,111,98,97,114,58,32]).concat(HEX24__systemZdollars_u14(n_p0)), parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
    }
    else {
      F.line = 251;
      result_1006632971 = mulInt(n_p0, 2);
    }
    
  framePtr = F.prev;

  return result_1006632971;

}

function HEX3Aanonymous__asyncjs95examples952_u36(r_p0) {
  var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
    F.line = 251;
    F.filename = "asyncjs.nim";
    this.reason0 = r_p0;
  framePtr = F.prev;

  
}

function sysFatal__stdZassertions_u41(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u39(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u41(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u81(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u39(msg_p0);
  framePtr = F.prev;

  
}

function HEX3Aanonymous__asyncjs95examples952_u74(r_p0) {
  var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
    F.line = 251;
    F.filename = "asyncjs.nim";
    this.reason0 = r_p0;
  framePtr = F.prev;

  
}

function nsuFindChar(s_p0, sub_p1, start_p2, last_p3) {
    var Temporary1;

  var result_1023411879 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1972;
    F.filename = "strutils.nim";
    result_1023411879 = (-1);
    F.line = 1973;
    if ((last_p3 < 0)) {
    Temporary1 = (s_p0).length - 1;
    }
    else {
    Temporary1 = last_p3;
    }
    
    var last_1023411880 = Temporary1;
    Label2: {
      F.line = 1976;
      var iHEX60gensym174_1023411894 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__1006633132 = 0;
      F.line = 1976;
      F.filename = "strutils.nim";
      colontmp__1006633132 = start_p2;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_1006633133 = colontmp__1006633132;
      Label3: {
        F.line = 97;
          Label4: while (true) {
          if (!(res_1006633133 <= last_1023411880)) break Label4;
            F.line = 1990;
            F.filename = "strutils.nim";
            iHEX60gensym174_1023411894 = res_1006633133;
            if ((s_p0[chckIndx(iHEX60gensym174_1023411894, 0, (s_p0).length - 1)] == sub_p1)) {
            F.line = 1978;
            result_1023411879 = iHEX60gensym174_1023411894;
            break BeforeRet;
            }
            
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_1006633133 = addInt(res_1006633133, 1);
          }
      };
    };
  };
  framePtr = F.prev;

  return result_1023411879;

}

function nsuFindStrA(a_p0, s_p1, sub_p2, start_p3, last_p4) {
    var Temporary1;

  var result_1023411858 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1932;
    F.filename = "strutils.nim";
    if ((last_p4 < 0)) {
    Temporary1 = (s_p1).length - 1;
    }
    else {
    Temporary1 = last_p4;
    }
    
    var last_1023411859 = Temporary1;
    F.line = 1933;
    var subLast_1023411860 = subInt((sub_p2).length, 1);
    if ((subLast_1023411860 == (-1))) {
    F.line = 1938;
    result_1023411858 = start_p3;
    break BeforeRet;
    }
    
    F.line = 1942;
    result_1023411858 = (-1);
    F.line = 1943;
    var skip_1023411861 = start_p3;
    Label2: {
      F.line = 1945;
        Label3: while (true) {
        if (!(subLast_1023411860 <= subInt(last_1023411859, skip_1023411861))) break Label3;
          F.line = 1946;
          var i_1023411862 = subLast_1023411860;
          Label4: {
            F.line = 1947;
              Label5: while (true) {
              if (!(s_p1[chckIndx(addInt(skip_1023411861, i_1023411862), 0, (s_p1).length - 1)] == sub_p2[chckIndx(i_1023411862, 0, (sub_p2).length - 1)])) break Label5;
                if ((i_1023411862 == 0)) {
                F.line = 1949;
                result_1023411858 = skip_1023411861;
                break BeforeRet;
                }
                
                F.line = 1950;
                i_1023411862 = subInt(i_1023411862, 1);
              }
          };
          F.line = 1951;
          skip_1023411861 = addInt(skip_1023411861, a_p0[chckIndx(s_p1[chckIndx(addInt(skip_1023411861, subLast_1023411860), 0, (s_p1).length - 1)], 0, (a_p0).length - 1)]);
        }
    };
  };
  framePtr = F.prev;

  return result_1023411858;

}

function fill__pureZstrutils_u1622(a_p0, value_p1) {
  var F = {procname: "fill.fill", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
  framePtr = F;
    F.line = 72;
    F.filename = "algorithm.nim";
    var xHEX60gensym170_1023411807 = 0;
    Label1: {
      F.line = 98;
        Label2: while (true) {
        if (!(xHEX60gensym170_1023411807 <= (a_p0).length - 1)) break Label2;
          F.line = 98;
          a_p0[chckIndx(xHEX60gensym170_1023411807, 0, (a_p0).length - 1)] = value_p1;
          F.line = 75;
          xHEX60gensym170_1023411807 = addInt(xHEX60gensym170_1023411807, 1);
        }
    };
  framePtr = F.prev;

  
}

function nsuInitSkipTable(a_p0, sub_p1) {
  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1905;
    F.filename = "strutils.nim";
    var m_1023411797 = (sub_p1).length;
    F.line = 1906;
    fill__pureZstrutils_u1622(a_p0, m_1023411797);
    Label1: {
      F.line = 1908;
      var i_1023411817 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__1006633138 = 0;
      F.line = 1908;
      F.filename = "strutils.nim";
      colontmp__1006633138 = subInt(m_1023411797, 1);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_1006633139 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_1006633139 < colontmp__1006633138)) break Label3;
            F.line = 1908;
            F.filename = "strutils.nim";
            i_1023411817 = i_1006633139;
            F.line = 1909;
            a_p0[chckIndx(sub_p1[chckIndx(i_1023411817, 0, (sub_p1).length - 1)], 0, (a_p0).length - 1)] = subInt(subInt(m_1023411797, 1), i_1023411817);
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_1006633139 = addInt(i_1006633139, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function nsuInitNewSkipTable(sub_p0) {
  var result_1023411851 = [new Int32Array(256)];

  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1918;
    F.filename = "strutils.nim";
    nsuInitSkipTable(result_1023411851[0], sub_p0);
  framePtr = F.prev;

  return result_1023411851[0];

}

function nsuFindStr(s_p0, sub_p1, start_p2, last_p3) {
  var result_1023411916 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((subInt((s_p0).length, start_p2) < (sub_p1).length)) {
    F.line = 2032;
    F.filename = "strutils.nim";
    result_1023411916 = (-1);
    break BeforeRet;
    }
    
    if (((sub_p1).length == 1)) {
    F.line = 2033;
    result_1023411916 = nsuFindChar(s_p0, sub_p1[chckIndx(0, 0, (sub_p1).length - 1)], start_p2, last_p3);
    break BeforeRet;
    }
    
    F.line = 2036;
    result_1023411916 = nsuFindStrA(nsuInitNewSkipTable(sub_p1), s_p0, sub_p1, start_p2, last_p3);
  };
  framePtr = F.prev;

  return result_1023411916;

}

function contains__pureZstrutils_u1878(s_p0, sub_p1) {
  var result_1023412057 = false;

  var F = {procname: "strutils.contains", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 2190;
    F.filename = "strutils.nim";
    result_1023412057 = (0 <= nsuFindStr(s_p0, sub_p1, 0, (-1)));
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_1023412057;

}
async function main__asyncjs95examples952_u26() {
    var Temporary1;
    var Temporary2;

  var result_1006632988 = null;

  var F = {procname: "asyncjs_examples_2.main", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 251;
    F.filename = "asyncjs.nim";
    var HEX3Aenv_1006633063 = null;
    F.line = 251;
    HEX3Aenv_1006633063 = {m_type: NTI1006633044, reason0: null};
    HEX3Aenv_1006633063.reason0 = null;
    F.line = 251;
    Temporary1 = HEX3Aanonymous__asyncjs95examples952_u36.bind(HEX3Aenv_1006633063); Temporary1.ClP_0 = HEX3Aanonymous__asyncjs95examples952_u36; Temporary1.ClE_0 = HEX3Aenv_1006633063;
    (await catch__asyncjs95examples952_u55(fn__asyncjs95examples952_u8(6), Temporary1));
    if (!((HEX3Aenv_1006633063.reason0 == null))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u81(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(19, 5) `reason == nil` "));
    }
    
    F.line = 251;
    Temporary2 = HEX3Aanonymous__asyncjs95examples952_u74.bind(HEX3Aenv_1006633063); Temporary2.ClP_0 = HEX3Aanonymous__asyncjs95examples952_u74; Temporary2.ClE_0 = HEX3Aenv_1006633063;
    (await catch__asyncjs95examples952_u55(fn__asyncjs95examples952_u8(7), Temporary2));
    if (!(!((HEX3Aenv_1006633063.reason0 == null)))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u81(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(21, 5) `reason != nil` "));
    }
    
    if (!(contains__pureZstrutils_u1878(cstrToNimstr(HEX3Aenv_1006633063.reason0.message), [102,111,111,98,97,114,58,32,55]))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u81(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(22, 5) `\"foobar: 7\" in $reason.message` "));
    }
    
    F.line = 251;
    result_1006632988 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_1006632988;

}
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
F.line = 251;
F.filename = "asyncjs.nim";
(main__asyncjs95examples952_u26());
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
