/* Generated by the Nim Compiler v1.7.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555813 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI134217745.base = NTI33555176;
var NNI33555813 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555813.node = NNI33555813;
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
NTI134217741.base = NTI33555176;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555176;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555176;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557073, src_33557074, ti_33557075) {
  var result_33557084 = null;

    switch (ti_33557075.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557064(ti_33557075))) {
      result_33557084 = src_33557074;
      }
      else {
        result_33557084 = [src_33557074[0], src_33557074[1]];
      }
      
      break;
    case 19:
            if (dest_33557073 === null || dest_33557073 === undefined) {
        dest_33557073 = {};
      }
      else {
        for (var key in dest_33557073) { delete dest_33557073[key]; }
      }
      for (var key in src_33557074) { dest_33557073[key] = src_33557074[key]; }
      result_33557084 = dest_33557073;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557075.base == null))) {
      result_33557084 = nimCopy(dest_33557073, src_33557074, ti_33557075.base);
      }
      else {
      if ((ti_33557075.kind == 17)) {
      result_33557084 = (dest_33557073 === null || dest_33557073 === undefined) ? {m_type: ti_33557075} : dest_33557073;
      }
      else {
        result_33557084 = (dest_33557073 === null || dest_33557073 === undefined) ? {} : dest_33557073;
      }
      }
      nimCopyAux(result_33557084, src_33557074, ti_33557075.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557074)) { 
        if(dest_33557073 === null || dest_33557073 === undefined || dest_33557073.length != src_33557074.length) {
          dest_33557073 = new src_33557074.constructor(src_33557074);
        } else {
          dest_33557073.set(src_33557074, 0);
        }
        result_33557084 = dest_33557073;
      } else {
        if (src_33557074 === null) {
          result_33557084 = null;
        }
        else {
          if (dest_33557073 === null || dest_33557073 === undefined || dest_33557073.length != src_33557074.length) {
            dest_33557073 = new Array(src_33557074.length);
          }
          result_33557084 = dest_33557073;
          for (var i = 0; i < src_33557074.length; ++i) {
            result_33557084[i] = nimCopy(result_33557084[i], src_33557074[i], ti_33557075.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557074 === null) {
        result_33557084 = null;
      }
      else {
        if (dest_33557073 === null || dest_33557073 === undefined || dest_33557073.length != src_33557074.length) {
          dest_33557073 = new Array(src_33557074.length);
        }
        result_33557084 = dest_33557073;
        for (var i = 0; i < src_33557074.length; ++i) {
          result_33557084[i] = nimCopy(result_33557084[i], src_33557074[i], ti_33557075.base);
        }
      }
    
      break;
    case 28:
            if (src_33557074 !== null) {
        result_33557084 = src_33557074.slice(0);
      }
    
      break;
    default: 
      result_33557084 = src_33557074;
      break;
    }

  return result_33557084;

}

function arrayConstr(len_33557112, value_33557113, typ_33557114) {
        var result = new Array(len_33557112);
    for (var i = 0; i < len_33557112; ++i) result[i] = nimCopy(null, value_33557113, typ_33557114);
    return result;
  

  
}

function mnewString(len_33556826) {
        return new Array(len_33556826);
  

  
}

function addInt(a_33556873, b_33556874) {
        var result = a_33556873 + b_33556874;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557122, a_33557123, b_33557124) {
  var result_33557125 = 0;

  BeforeRet: {
    if (((a_33557123 <= i_33557122) && (i_33557122 <= b_33557124))) {
    result_33557125 = i_33557122;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557125;

}

function chckIndx(i_33557117, a_33557118, b_33557119) {
  var result_33557120 = 0;

  BeforeRet: {
    if (((a_33557118 <= i_33557117) && (i_33557117 <= b_33557119))) {
    result_33557120 = i_33557117;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557117, a_33557118, b_33557119);
    }
    
  };

  return result_33557120;

}

function cstrToNimstr(c_33556734) {
      var ln = c_33556734.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556734.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556734.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556737) {
  var result_33556738 = null;

    var res_33556772 = newSeq_33556755((s_33556737).length);
    var i_33556773 = 0;
    var j_33556774 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556773 < (s_33556737).length)) break Label2;
          var c_33556775 = s_33556737[i_33556773];
          if ((c_33556775 < 128)) {
          res_33556772[j_33556774] = String.fromCharCode(c_33556775);
          i_33556773 += 1;
          }
          else {
            var helper_33556788 = newSeq_33556755(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556789 = c_33556775.toString(16);
                  if ((((code_33556789) == null ? 0 : (code_33556789).length) == 1)) {
                  helper_33556788.push("%0");;
                  }
                  else {
                  helper_33556788.push("%");;
                  }
                  
                  helper_33556788.push(code_33556789);;
                  i_33556773 += 1;
                  if ((((s_33556737).length <= i_33556773) || (s_33556737[i_33556773] < 128))) {
                  break Label3;
                  }
                  
                  c_33556775 = s_33556737[i_33556773];
                }
            };
++excHandler;
            try {
            res_33556772[j_33556774] = decodeURIComponent(helper_33556788.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556772[j_33556774] = helper_33556788.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556774 += 1;
        }
    };
    if (res_33556772.length < j_33556774) { for (var i = res_33556772.length ; i < j_33556774 ; ++i) res_33556772.push(null); }
               else { res_33556772.length = j_33556774; };
    result_33556738 = res_33556772.join("");

  return result_33556738;

}

function raiseException(e_33556597, ename_33556598) {
    e_33556597.name = ename_33556598;
    if ((excHandler == 0)) {
    unhandledException(e_33556597);
    }
    
    e_33556597.trace = nimCopy(null, rawWriteStackTrace_33556561(), NTI33554449);
    throw e_33556597;

  
}

function makeNimstrLit(c_33556731) {
      var result = [];
  for (var i = 0; i < c_33556731.length; ++i) {
    result[i] = c_33556731.charCodeAt(i);
  }
  return result;
  

  
}

function eqStrings(a_33556864, b_33556865) {
        if (a_33556864 == b_33556865) return true;
    if (a_33556864 === null && b_33556865.length == 0) return true;
    if (b_33556865 === null && a_33556864.length == 0) return true;
    if ((!a_33556864) || (!b_33556865)) return false;
    var alen = a_33556864.length;
    if (alen != b_33556865.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_33556864[i] != b_33556865[i]) return false;
    return true;
  

  
}

function subInt(a_33556877, b_33556878) {
        var result = a_33556877 - b_33556878;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557064(ti_33557065) {
  var result_33557066 = false;

  BeforeRet: {
    result_33557066 = !((ConstSet1[ti_33557065.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557066;

}

function nimCopyAux(dest_33557077, src_33557078, n_33557079) {
    switch (n_33557079.kind) {
    case 0:
      break;
    case 1:
            dest_33557077[n_33557079.offset] = nimCopy(dest_33557077[n_33557079.offset], src_33557078[n_33557079.offset], n_33557079.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557079.sons.length; i++) {
      nimCopyAux(dest_33557077, src_33557078, n_33557079.sons[i]);
    }
    
      break;
    case 3:
            dest_33557077[n_33557079.offset] = nimCopy(dest_33557077[n_33557079.offset], src_33557078[n_33557079.offset], n_33557079.typ);
      for (var i = 0; i < n_33557079.sons.length; ++i) {
        nimCopyAux(dest_33557077, src_33557078, n_33557079.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556385(x_33556386, x_33556386_Idx, y_33556387) {
          if (x_33556386[x_33556386_Idx] === null) { x_33556386[x_33556386_Idx] = []; }
      var off = x_33556386[x_33556386_Idx].length;
      x_33556386[x_33556386_Idx].length += y_33556387.length;
      for (var i = 0; i < y_33556387.length; ++i) {
        x_33556386[x_33556386_Idx][off+i] = y_33556387.charCodeAt(i);
      }
    

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556871) {
        if (a_33556871 > 2147483647 || a_33556871 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556684, a_33556685, b_33556686) {
    var Temporary1;

    if ((b_33556686 < a_33556685)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_352321544(i_33556684) || [],[32,110,111,116,32,105,110,32] || [],HEX24_352321544(a_33556685) || [],[32,46,46,32] || [],HEX24_352321544(b_33556686) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_285212850(result_285212852, result_285212852_Idx, x_285212853, start_285212854, n_285212855) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    var old_285212856 = (result_285212852[result_285212852_Idx]).length;
    F.line = 44;
    (result_285212852[result_285212852_Idx].length = chckRange(addInt(old_285212856, n_285212855), 0, 2147483647));
    Label1: {
      F.line = 46;
      var iHEX60gensym4_285212870 = 0;
      F.line = 119;
      var i_637534270 = 0;
      Label2: {
        F.line = 120;
          Label3: while (true) {
          if (!(i_637534270 < n_285212855)) break Label3;
            F.line = 49;
            iHEX60gensym4_285212870 = i_637534270;
            F.line = 49;
            result_285212852[result_285212852_Idx][chckIndx(addInt(old_285212856, iHEX60gensym4_285212870), 0, (result_285212852[result_285212852_Idx]).length - 1)] = x_285212853.charCodeAt(chckIndx(addInt(start_285212854, iHEX60gensym4_285212870), 0, (x_285212853).length - 1));
            F.line = 122;
            i_637534270 = addInt(i_637534270, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_285212846(result_285212848, result_285212848_Idx, x_285212849) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    addChars_285212850(result_285212848, result_285212848_Idx, x_285212849, 0, ((x_285212849) == null ? 0 : (x_285212849).length));
  framePtr = F.prev;

  
}

function addInt_285212871(result_285212872, result_285212872_Idx, x_285212873) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 113;
    addChars_285212846(result_285212872, result_285212872_Idx, ((x_285212873) + ""));
  framePtr = F.prev;

  
}

function addInt_285212892(result_285212893, result_285212893_Idx, x_285212894) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 117;
    addInt_285212871(result_285212893, result_285212893_Idx, x_285212894);
  framePtr = F.prev;

  
}

function HEX24_352321544(x_352321545) {
  var result_352321546 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    addInt_285212892(result_352321546, 0, x_352321545);
  framePtr = F.prev;

  return result_352321546[0];

}

function auxWriteStackTrace_33556486(f_33556487) {
  var result_33556488 = [[]];

    var it_33556496 = f_33556487;
    var i_33556497 = 0;
    var total_33556498 = 0;
    var tempFrames_33556499 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555813);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556496 == null)) && (i_33556497 <= 63))) break Label2;
          tempFrames_33556499[i_33556497].Field0 = it_33556496.procname;
          tempFrames_33556499[i_33556497].Field1 = it_33556496.line;
          tempFrames_33556499[i_33556497].Field2 = it_33556496.filename;
          i_33556497 += 1;
          total_33556498 += 1;
          it_33556496 = it_33556496.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556496 == null))) break Label4;
          total_33556498 += 1;
          it_33556496 = it_33556496.prev;
        }
    };
    result_33556488[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556498 == i_33556497))) {
    result_33556488[0].push.apply(result_33556488[0], [40]);;
    result_33556488[0].push.apply(result_33556488[0], HEX24_352321544((total_33556498 - i_33556497)));;
    result_33556488[0].push.apply(result_33556488[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556532 = 0;
      var colontmp__637534262 = 0;
      colontmp__637534262 = (i_33556497 - 1);
      var res_637534264 = colontmp__637534262;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_637534264)) break Label7;
            j_33556532 = res_637534264;
            result_33556488[0].push.apply(result_33556488[0], cstrToNimstr(tempFrames_33556499[j_33556532].Field2));;
            if ((0 < tempFrames_33556499[j_33556532].Field1)) {
            result_33556488[0].push.apply(result_33556488[0], [40]);;
            addInt_285212892(result_33556488, 0, tempFrames_33556499[j_33556532].Field1);
            if (false) {
            result_33556488[0].push.apply(result_33556488[0], [44,32]);;
            addInt_285212892(result_33556488, 0, 0);
            }
            
            result_33556488[0].push.apply(result_33556488[0], [41]);;
            }
            
            result_33556488[0].push.apply(result_33556488[0], [32,97,116,32]);;
            add_33556385(result_33556488, 0, tempFrames_33556499[j_33556532].Field0);
            result_33556488[0].push.apply(result_33556488[0], [10]);;
            res_637534264 -= 1;
          }
      };
    };

  return result_33556488[0];

}

function rawWriteStackTrace_33556561() {
  var result_33556562 = [];

    if (!((framePtr == null))) {
    result_33556562 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556486(framePtr) || []), NTI33554449);
    }
    else {
      result_33556562 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556562;

}

function newSeq_33556755(len_33556757) {
  var result_33556758 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 604;
    result_33556758 = new Array(len_33556757); for (var i = 0 ; i < len_33556757 ; ++i) { result_33556758[i] = null; }  framePtr = F.prev;

  return result_33556758;

}

function unhandledException(e_33556593) {
    var buf_33556594 = [[]];
    if (!(((e_33556593.message).length == 0))) {
    buf_33556594[0].push.apply(buf_33556594[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556594[0].push.apply(buf_33556594[0], e_33556593.message);;
    }
    else {
    buf_33556594[0].push.apply(buf_33556594[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556594[0].push.apply(buf_33556594[0], [32,91]);;
    add_33556385(buf_33556594, 0, e_33556593.name);
    buf_33556594[0].push.apply(buf_33556594[0], [93,10]);;
    buf_33556594[0].push.apply(buf_33556594[0], rawWriteStackTrace_33556561());;
    var cbuf_33556595 = toJSStr(buf_33556594[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556595);
  }
  else {
    throw cbuf_33556595;
  }
  

  
}

function raiseAssert_251658262(msg_251658263) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 31;
    raiseException({message: nimCopy(null, msg_251658263, NTI33554449), parent: null, m_type: NTI134217745, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function failedAssertImpl_251658292(msg_251658293) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    raiseAssert_251658262(msg_251658293);
  framePtr = F.prev;

  
}
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
if (!((BigInt(1234567890) == BigInt("1234567890")))) {
F.line = 14;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(8, 12) `big(1234567890) == big\"1234567890\"` "));
}

if (!(((BigInt(999) == BigInt(999)) && (BigInt(999) == BigInt(999))))) {
F.line = 14;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(9, 12) `0b00000000000000000000001111100111.big == 0o000000001747.big and\x0A    0o000000001747.big == 999.big` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
if (!((BigInt("-1") == (BigInt("1") - BigInt("2"))))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(8, 12) `-1\'big == 1\'big - 2\'big` "));
}

if (!((BigInt("-12") == BigInt("-12")))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(10, 12) `-12\'big == big\"-12\"` "));
}

if (!((BigInt("12") == BigInt(12)))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(11, 12) `12\'big == 12.big` "));
}

if (!((BigInt("0b101") == BigInt(5)))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(12, 12) `0b101\'big == 0b00000000000000000000000000000101.big` "));
}

if (!((BigInt("0o701") == BigInt(449)))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(13, 12) `0o701\'big == 0o000000000701.big` "));
}

if (!((BigInt("0xdeadbeaf") == BigInt(3735928495)))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(14, 12) `0xdeadbeaf\'big == 0x00000000DEADBEAF\'i64.big` "));
}

if (!((BigInt("0xffffffffffffffff") == ((BigInt("1") << BigInt("64")) - BigInt("1"))))) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(15, 12) `0xffffffffffffffff\'big == (1\'big shl 64\'big) - 1\'big` "));
}

if (false) {
F.line = 21;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(16, 3) `not compiles(static(12\'big))` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
if (!((BigInt("2147483647").toString(2) == "1111111111111111111111111111111"))) {
F.line = 41;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim(8, 12) `big\"2147483647\".toCstring(2) == \"1111111111111111111111111111111\".cstring` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX24_654311453(this_654311454) {
  var result_654311455 = [];

  var F = {procname: "jsbigints.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
  framePtr = F;
    F.line = 49;
    result_654311455 = nimCopy(null, (cstrToNimstr(this_654311454.toString()) || []).concat([110]), NTI33554449);
  framePtr = F.prev;

  return result_654311455;

}
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
if (!(eqStrings(HEX24_654311453(BigInt("1024")), [49,48,50,52,110]))) {
F.line = 50;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim(8, 12) `$big\"1024\" == \"1024n\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 13; return BigInt.asIntN(b, i) })() == BigInt("3")))) {
F.line = 57;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim(8, 12) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToInt(13) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 66; return BigInt.asUintN(b, i) })() == BigInt("3")))) {
F.line = 64;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim(8, 12) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToUint(66) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
if (!((Number(BigInt("2147483647")) == 2147483647))) {
F.line = 69;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim(8, 12) `toNumber(big\"2147483647\") == 2147483647.BiggestInt` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") + BigInt("1")) == BigInt("10")))) {
F.line = 73;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim(8, 12) `(big\"9\" + big\"1\") == big\"10\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") - BigInt("1")) == BigInt("8")))) {
F.line = 77;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim(8, 12) `(big\"9\" - big\"1\") == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
if (!(((BigInt("42") * BigInt("9")) == BigInt("378")))) {
F.line = 81;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim(8, 12) `(big\"42\" * big\"9\") == big\"378\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") / BigInt("3")) == BigInt("4")))) {
F.line = 86;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(8, 12) `big\"13\" div big\"3\" == big\"4\"` "));
}

if (!(((BigInt("-13") / BigInt("3")) == BigInt("-4")))) {
F.line = 86;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(9, 12) `big\"-13\" div big\"3\" == big\"-4\"` "));
}

if (!(((BigInt("13") / BigInt("-3")) == BigInt("-4")))) {
F.line = 86;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(10, 12) `big\"13\" div big\"-3\" == big\"-4\"` "));
}

if (!(((BigInt("-13") / BigInt("-3")) == BigInt("4")))) {
F.line = 86;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(11, 12) `big\"-13\" div big\"-3\" == big\"4\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") % BigInt("3")) == BigInt("1")))) {
F.line = 94;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(8, 12) `big\"13\" mod big\"3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("3")) == BigInt("-1")))) {
F.line = 94;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(9, 12) `big\"-13\" mod big\"3\" == big\"-1\"` "));
}

if (!(((BigInt("13") % BigInt("-3")) == BigInt("1")))) {
F.line = 94;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(10, 12) `big\"13\" mod big\"-3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("-3")) == BigInt("-1")))) {
F.line = 94;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(11, 12) `big\"-13\" mod big\"-3\" == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
if (!((BigInt("2") < BigInt("9")))) {
F.line = 101;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim(8, 12) `big\"2\" < big\"9\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
if (!((BigInt("1") <= BigInt("5")))) {
F.line = 105;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim(8, 12) `big\"1\" <= big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
if (!((BigInt("42") == BigInt("42")))) {
F.line = 109;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim(8, 12) `big\"42\" == big\"42\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
if (!((((BigInt("2")) ** BigInt("64")) == BigInt("18446744073709551616")))) {
F.line = 114;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(8, 12) `big\"2\" ** big\"64\" == big\"18446744073709551616\"` "));
}

if (!((((BigInt("-2")) ** BigInt("3")) == BigInt("-8")))) {
F.line = 114;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(9, 12) `big\"-2\" ** big\"3\" == big\"-8\"` "));
}

if (!(((((-BigInt("2"))) ** BigInt("2")) == BigInt("4")))) {
F.line = 114;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(10, 12) `-big\"2\" ** big\"2\" == big\"4\"` "));
}

if (!((((BigInt("0")) ** BigInt("0")) == BigInt("1")))) {
F.line = 114;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(11, 12) `big\"0\" ** big\"0\" == big\"1\"` "));
}

F.line = 114;
var ok_905969686 = [false];
F.line = 114;
++excHandler;
try {
F.line = 114;
var _ = ((BigInt("2")) ** BigInt("-1"));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
framePtr = F;
F.line = 114;
ok_905969686[0] = true;
lastJSError = prevJSError;
} finally {
framePtr = F;
}
if (!(ok_905969686[0])) {
F.line = 114;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(15, 12) `ok` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") & BigInt("2")) == BigInt("2")))) {
F.line = 127;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim(8, 12) `(big\"555\" and big\"2\") == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") | BigInt("2")) == BigInt("555")))) {
F.line = 131;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim(8, 12) `(big\"555\" or big\"2\") == big\"555\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") ^ BigInt("2")) == BigInt("553")))) {
F.line = 135;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim(8, 12) `(big\"555\" xor big\"2\") == big\"553\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") << BigInt("2")) == BigInt("3996")))) {
F.line = 139;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim(8, 12) `(big\"999\" shl big\"2\") == big\"3996\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") >> BigInt("2")) == BigInt("249")))) {
F.line = 143;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim(8, 12) `(big\"999\" shr big\"2\") == big\"249\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
if (!(((-BigInt("10101010101")) == BigInt("-10101010101")))) {
F.line = 147;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim(8, 12) `-(big\"10101010101\") == big\"-10101010101\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
F.line = 151;
var big1_1023410178 = [BigInt("1")];
F.line = 151;
(++[big1_1023410178, 0][0][0]);
if (!((big1_1023410178[0] == BigInt("2")))) {
F.line = 151;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim(10, 12) `big1 == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
F.line = 157;
var big1_1040187394 = [BigInt("2")];
F.line = 157;
(--[big1_1040187394, 0][0][0]);
if (!((big1_1040187394[0] == BigInt("1")))) {
F.line = 157;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim(10, 12) `big1 == big\"1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
F.line = 163;
var big1_1056964610 = [BigInt("1")];
F.line = 163;
([big1_1056964610, 0][0][0] += BigInt("2"));
if (!((big1_1056964610[0] == BigInt("3")))) {
F.line = 163;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim(10, 12) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
F.line = 169;
var big1_1073741826 = [BigInt("1")];
F.line = 169;
([big1_1073741826, 0][0][0] -= BigInt("2"));
if (!((big1_1073741826[0] == BigInt("-1")))) {
F.line = 169;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim(10, 12) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
F.line = 175;
var big1_1090519042 = [BigInt("1")];
F.line = 175;
([big1_1090519042, 0][0][0] += BigInt("2"));
if (!((big1_1090519042[0] == BigInt("3")))) {
F.line = 175;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim(10, 12) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
F.line = 181;
var big1_1107296258 = [BigInt("1")];
F.line = 181;
([big1_1107296258, 0][0][0] -= BigInt("2"));
if (!((big1_1107296258[0] == BigInt("-1")))) {
F.line = 181;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim(10, 12) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
F.line = 187;
var big1_1124073474 = [BigInt("2")];
F.line = 187;
([big1_1124073474, 0][0][0] *= BigInt("4"));
if (!((big1_1124073474[0] == BigInt("8")))) {
F.line = 187;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim(10, 12) `big1 == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
F.line = 194;
var big1_1140850690 = [BigInt("11")];
F.line = 194;
([big1_1140850690, 0][0][0] /= BigInt("2"));
if (!((big1_1140850690[0] == BigInt("5")))) {
F.line = 194;
failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim(10, 12) `big1 == big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX3DHEX3D_1157627963(x_1157627965, y_1157627966) {
  var result_1157627967 = false;

  var F = {procname: "==.==", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/comparisons.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 326;
    var sameObject_1157627975 = false;
    F.line = 327;
    sameObject_1157627975 = x_1157627965 === y_1157627966
    if (sameObject_1157627975) {
    F.line = 328;
    result_1157627967 = true;
    break BeforeRet;
    }
    
    if (!(((x_1157627965).length == (y_1157627966).length))) {
    F.line = 331;
    result_1157627967 = false;
    break BeforeRet;
    }
    
    Label1: {
      F.line = 333;
      var i_1157627989 = 0;
      F.line = 75;
      var colontmp__1157628063 = 0;
      F.line = 333;
      colontmp__1157628063 = subInt((x_1157627965).length, 1);
      F.line = 90;
      var res_1157628065 = 0;
      Label2: {
        F.line = 91;
          Label3: while (true) {
          if (!(res_1157628065 <= colontmp__1157628063)) break Label3;
            F.line = 333;
            i_1157627989 = res_1157628065;
            if (!((x_1157627965[chckIndx(i_1157627989, 0, (x_1157627965).length - 1)] == y_1157627966[chckIndx(i_1157627989, 0, (y_1157627966).length - 1)]))) {
            F.line = 335;
            result_1157627967 = false;
            break BeforeRet;
            }
            
            F.line = 93;
            res_1157628065 = addInt(res_1157628065, 1);
          }
      };
    };
    F.line = 337;
    result_1157627967 = true;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_1157627967;

}

function HEX5BHEX5D_1157627995(s_1157627997, i_1157627998) {
  var result_1157627999 = null;
  var result_1157627999_Idx = 0;

  var F = {procname: "[].[]", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/indices.nim", line: 0};
  framePtr = F;
    F.line = 30;
    result_1157627999 = s_1157627997; result_1157627999_Idx = chckIndx(subInt((s_1157627997).length, i_1157627998), 0, (s_1157627997).length - 1);
  framePtr = F.prev;

  return [result_1157627999, result_1157627999_Idx];

}
    var Temporary4;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
Label2: {
  F.line = 210;
  var big1_1157627906 = BigInt("2147483647");
  F.line = 210;
  var big2_1157627907 = BigInt("666");
  if (false) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(11, 14) `JsBigInt isnot int` "));
  }
  
  if (!(!((big1_1157627906 == big2_1157627907)))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(12, 14) `big1 != big2` "));
  }
  
  if (!((big2_1157627907 < big1_1157627906))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(13, 14) `big1 > big2` "));
  }
  
  if (!((big2_1157627907 <= big1_1157627906))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(14, 14) `big1 >= big2` "));
  }
  
  if (!((big2_1157627907 < big1_1157627906))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(15, 14) `big2 < big1` "));
  }
  
  if (!((big2_1157627907 <= big1_1157627906))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(16, 14) `big2 <= big1` "));
  }
  
  if (!(!((big1_1157627906 == big2_1157627907)))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(17, 5) `not (big1 == big2)` "));
  }
  
  F.line = 210;
  var z_1157627948 = 0n;
  if (!(eqStrings(HEX24_654311453(z_1157627948), [48,110]))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(19, 14) `$z == \"0n\"` "));
  }
  
};
Label3: {
  F.line = 210;
  var a_1157627954 = [[]];
  F.line = 210;
  if (a_1157627954[0].length < 2) { for (var i = a_1157627954[0].length ; i < 2 ; ++i) a_1157627954[0].push(0n); }
               else { a_1157627954[0].length = 2; };
  if (!(HEX3DHEX3D_1157627963(a_1157627954[0], [BigInt("0"), BigInt("0")]))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(23, 14) `a == @[big\"0\", big\"0\"]` "));
  }
  
  if (!(((Temporary4 = HEX5BHEX5D_1157627995(a_1157627954[0], 1), Temporary4)[0][Temporary4[1]] == BigInt("0")))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(24, 14) `a[^1] == big\"0\"` "));
  }
  
  F.line = 210;
  var b_1157628018 = [0n];
  if (!((b_1157628018[0] == BigInt("0")))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(26, 14) `b == big\"0\"` "));
  }
  
  if (!((b_1157628018[0] == 0n))) {
  F.line = 210;
  failedAssertImpl_251658292(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(27, 14) `b == JsBigInt.default` "));
  }
  
};
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
