#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jscore.nim(131, 5)
rdoccmd: 
]#
import "/home/runner/work/Nim/Nim/lib/js/jscore.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/js/jscore.nim", 131, 5).}:
  var arrai = @[1, 2, 3]
  assert arrai.shift() == 1
  assert arrai == @[2, 3]

