#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jscore.nim(139, 21)
rdoccmd: -r:off
]#
import "/home/runner/work/Nim/Nim/lib/js/jscore.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/js/jscore.nim", 139, 21).}:
  queueMicrotask(proc() = echo "Microtask")

